name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: ["*"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64,linux/arm/v8,linux/amd64
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}  
         
      - name: Build the Docker image - date
        run: docker buildx build . --file Dockerfile --platform linux/arm64,linux/arm/v8,linux/amd64 --tag primeroz/unpoller:$(date +%s) --push

      - name: Build the Docker image - latest
        if: github.ref_name == 'v*' || github.ref_name == 'main'
        run: docker buildx build . --file Dockerfile --platform linux/arm64,linux/arm/v8,linux/amd64 --tag primeroz/unpoller:latest --push

      - name: Build the Docker image - tag
        if: github.ref_name == 'v*'
        run: docker buildx build . --file Dockerfile --platform linux/arm64,linux/arm/v8,linux/amd64 --tag primeroz/unpoller:${{github.ref_name}} --push
